#Security 用户名/密码
security:
  user:
    name: admin
    password: robot
    role: ADMIN


#MySQL 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/robot
    username: root
    password: root
    pool-name: SpringBootHikariCP
    maximum-pool-size: 50
    minimum-idle: 5
    max-lifetime: 1800000
    connection-timeout: 30000
    idle-timeout: 30000
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update


#server 端口/session超时时间
server:
  port: 5000
  session:
    timeout: 1200